# Main Process
Stochastic Model + Nonlinear Model + Resilience Assessment

In [1]:
# import modules
import numpy as np
import pandas as pd
import openseespy as ops
import pathlib
import pickle
import random
# module for SGMM

# module for NTHA
from BuildingObject import Building_object
from beam_component import Beam
from column_component import Column
from steel_material import SteelMaterial
from nonlinear_analysis import NonlinearAnalysis
from StochasticGroundMotionModeling import StochasticGroundMotionModeling
from loss_calculation import Data

In [2]:
# BASE INFORMATION
cwdFile = pathlib.Path.cwd()
buildingDataFile = cwdFile /'BuildingData'
geometryFile = buildingDataFile / 'Geometry.csv'
memberSizeFile = buildingDataFile / 'MemberSize.csv'
loadsFile = buildingDataFile / 'Loads.csv'

member_size = pd.read_csv(memberSizeFile)
gravity_loads = pd.read_csv(loadsFile)
directory = {}
directory = {'building data': buildingDataFile}
building = Building_object(directory, member_size, gravity_loads)

# beams
beamSizeFile = buildingDataFile / 'beamsectionsize.csv'
SectionDatabaseFile = cwdFile / 'AllSectionDatabase.csv'
SectionDatabase = pd.read_csv(SectionDatabaseFile)

steel = SteelMaterial(yield_stress=50, ultimate_stress=65, elastic_modulus=29000, 
                      Ry_value=1.1)  # Unit: ksi
# 创建包含梁信息的嵌套字典
beam_section_size = pd.read_csv(beamSizeFile)
beams = {}
length = int(building.geometry['X bay width'])
for _, row in beam_section_size.iterrows():
    level, bay = map(int, row[:2])
    bsection_size = {'size': row[2]}
    beams.setdefault(level, {})
    beams[level].setdefault(bay, {})
    beams[level][bay] = Beam(bsection_size['size'], length, steel,SectionDatabase)
    
# elastic demand
elasticDemandFile = cwdFile / 'elastic_demand.pkl'
with open(elasticDemandFile, 'rb') as f:
    elastic_demand = pickle.load(f)

# column
columnSizeFile = buildingDataFile / 'columnsectionsize.csv'
SectionDatabaseFile = cwdFile / 'AllSectionDatabase.csv'
SectionDatabase = pd.read_csv(SectionDatabaseFile)

steel = SteelMaterial(yield_stress=50, ultimate_stress=65, elastic_modulus=29000, 
                      Ry_value=1.1)  # Unit: ksi

# 构建包含柱信息的嵌套字典
column_section_size = pd.read_csv(columnSizeFile)
columns = {}
for _, row in column_section_size.iterrows():
    story, pier = map(int, row[:2])
    csection_size = {'size': row[2]}
    columns.setdefault(story, {})
    columns[story].setdefault(bay, {})
    axial_demand = abs(elastic_demand.dominate_load['column axial'][story, 2 * pier])
    Lx = (building.geometry['floor height'][story+1] - building.geometry['floor height'][story]).item()
    Ly = Lx
    columns[story][pier] = Column(csection_size['size'], axial_demand, Lx, Ly, steel, SectionDatabase)

baseFile = cwdFile

In [3]:
nSample = 1
edpOutput = np.zeros((nSample, 8))
costOutput = np.zeros(nSample)
np.random.seed(2)  # 确保结果可以复现
for i in range(nSample):
    print(i)
    # whichone = random.randint(0, 999)
    ACC, tn = StochasticGroundMotionModeling(7.62, 19.3, 602, 0)
    # NTHA
    dt = 0.01
    ACC = ACC.tolist()
    edpResult = NonlinearAnalysis(building, columns, beams, baseFile, ACC, dt)
    edpOutput[i, :] = edpResult
    print(edpResult)
    data = Data()
    IDR = edpResult[:3]
    PFA = edpResult[3:7]
    frameCost, sframeCost, nframeCost, cframeCost = data.cal_repair(IDR, PFA)
    print(frameCost)
    costOutput[i] = frameCost

0


Modified Ibarra-Medina-Krawinkler Model with Bilinear Hysteretic Response


Analysis Completed!
[0.00487869 0.00476931 0.00265371 0.28023853 0.19000926 0.19075288
 0.22818147 0.0010101 ]
72814.20669990484


In [1]:
import numpy as np
from loss_calculation import Data
n = 100
c = np.empty(n)
data = Data()
IDR = np.array([0.00487869, 0.00476931, 0.00265371])
PFA = np.array([0.28023853, 0.19000926, 0.19075288, 0.22818147])
RIDR = 0.0010101
costReplace = 1e6
nSample = 1000
costOut_list, costOut_mean = data.costOut(IDR, PFA, RIDR, costReplace, nSample)
print(costOut_mean)
costOut_list

134425.42669114823


array([200603.49202257,  54275.45875844, 189138.95503871, 127142.56554461,
        82467.59600206,  66452.97803641, 116619.78371715, 105249.48045121,
        62944.12798894,  35934.78882397, 100238.63495562, 230411.42925405,
       124669.28895445, 194763.21276355, 137700.46103931,  34039.31725455,
       138451.49430308, 137367.53829678, 191973.45728981, 142705.04111997,
       185119.79333211,  73222.52815318, 101331.91855039, 274370.21131846,
       113055.14792725, 134864.23668763, 124946.1295432 , 124099.18478136,
       326590.01623226,  95840.35508644,  66947.10628235,  75121.86377259,
       231559.16001669, 118810.78764433, 182453.02200856, 138020.50611844,
       105880.15605349, 125649.49814744,  89003.95318258, 179889.4489242 ,
       249036.84815383,  99398.3498189 ,  86258.52229926, 190313.29349041,
       101328.4958041 ,  70119.04219045, 245184.8167972 , 165679.74968263,
        99331.01096201,  79144.52052261, 185010.27093843,  17142.63680526,
       203775.4264447 , 1

In [6]:
import numpy as np
a = np.linspace(1,10,10)
print(a)
np.random.shuffle(a)
print(a)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
[ 8.  6.  7.  4.  2.  1.  3. 10.  5.  9.]


In [ ]:
# import pickle
# import os
# os.chdir(cwdFile)
# file = open('edpOutput.pickle', 'wb')
# pickle.dump(edpOutput, file)
# file.close()

# file = open('costOutput.pickle', 'wb')
# pickle.dump(costOutput, file)
# file.close()

In [ ]:
# with open('edpOutput.pickle', 'rb') as file:
#     dict_get = pickle.load(file)
# print(dict_get)

In [ ]:
# import matplotlib.pyplot as plt
# plt.hist(costOutput, bins=50)

In [ ]:
# IDR = np.array([4.89864183e-03, 4.80458308e-03, 2.76950154e-03])
# PFA = np.array([3.77184274e-01, 1.96116983e-01, 1.82918742e-01, 2.32016048e-01])
# data = Data()
# np.random.seed(1)  # 确保结果可以复现
# frameCost, sframeCost, nframeCost, cframeCost = data.cal_repair(IDR, PFA)
# frameCost

In [ ]:
# # SGMM
# from StochasticGroundMotionModeling import StochasticGroundMotionModeling
# import matplotlib.pyplot as plt
# # StochasticGroundMotionModeling(M, R, Vs, whichone, num=100, tn=40, F=1)
# ACC, tn = StochasticGroundMotionModeling(6.61, 19.3, 602, 0)
# t = np.arange(0, tn + 0.01, 0.01)
# plt.plot(t, ACC, linewidth=0.5)
# plt.xlabel('time (s)')
# plt.ylabel('acc (g)')
# plt.title('acc history')
# plt.grid(True)
# plt.show()

In [ ]:
# # NTHA
# dt = 0.01
# ACC = ACC.tolist()
# edpResult = NonlinearAnalysis(building, columns, beams, baseFile, ACC, dt)

In [ ]:
# print(edpResult)

In [ ]:
# edpResult[3:7]

In [ ]:
# from loss_calculation import Data
# data = Data()
# IDR = edpResult[:3]
# PFA = edpResult[3:7]
# frameCost, sframeCost, nframeCost, cframeCost = data.cal_repair(IDR, PFA)

In [ ]:
# frameCost

In [ ]:
# import matplotlib.pyplot as plt
# import numpy as np
# t = np.arange(0, 4001*0.01+0.002, 0.001)

# print(t.shape)
# print(U.shape)
# plt.figure(figsize = (12,4))
# plt.plot(t, U, linewidth = 1)