In [1]:
from StochasticGroundMotionModeling import StochasticGroundMotionModeling
StochasticGroundMotionModeling(6.61, 19.3, 602, 1, 100)

c:\ProgramData\miniconda3\envs\py310r\lib\site-packages\numpy\core\fromnumeric.py:86: RuntimeWarning: overflow encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
c:\Users\12734\OneDrive\重要文件\2_SensitivityAnalysis\Sensitivity-PythonCode\sensitivity-code\ResilienceAssessment\MainProcess\StochasticGroundMotionModeling.py:140: RuntimeWarning: overflow encountered in square
  hjd2 = hid**2


In [1]:
import numpy as np

In [11]:
a = np.array([[1,2,3],[8,3,9],[3,5,19]])  # 2 x 3
amax = np.max(a, axis = 1)
amax

array([ 3,  9, 19])

In [19]:
c = a[:,2]
c

array([ 3,  9, 19])

In [27]:
from scipy.stats import lognorm
mean = 0.01
stddev = 0.5
dist = lognorm(s=stddev, scale=mean)
a = np.array([0.01,0.02,0.01])
# x = np.linspace(0, 0.01 * 2, 200)
# y = dist.cdf(x)
# objPercent = np.interp(0.02, x, y)
# objPercent = round(objPercent * 100)
objPercent = dist.cdf(a)
objPercent = np.round(objPercent * 100)
objPercent

array([50., 92., 50.])

In [33]:
nSample = 1000
objPercent = np.array([50, 92, 50])
probNoRepair = objPercent / 100
nNoRepair = (nSample * probNoRepair).astype(int)
Outputlist = np.zeros((3, 1000))
for i in nNoRepair:
    Outputlist[:, :i] = 1  
Outputlist[1,:][Outputlist[1,:]==1].shape

array([500, 920, 500])

In [38]:
Outputlist = np.zeros((3, 1000))
for i in nNoRepair:
    Outputlist[:, :i] = 1  
Outputlist[1,:][Outputlist[1,:]==1].shape

(920,)

In [40]:
import numpy as np

nSample = 1000
objPercent = np.array([50, 92, 50])
probNoRepair = objPercent / 100
nNoRepair = (nSample * probNoRepair).astype(int)
Outputlist = np.zeros((3, 1000))

# 使用广播和掩码来填充Outputlist
mask = np.arange(1000) < nNoRepair[:, np.newaxis]
Outputlist[mask] = 1

# # 检查Outputlist中第二行的非零元素数量
# non_zero_count = np.count_nonzero(Outputlist[1, :])
# print(non_zero_count)


920


In [1]:
import numpy as np
a = np.array([10,100,50])
b = np.zeros((100, 3, a))
b

TypeError: only integer scalar arrays can be converted to a scalar index

In [29]:
import numpy as np
a = np.array([0.3, 0.4, 0.5])
b = np.array([0.1, 0.3, 0.4])
c = np.stack([(1 - a), (a-b), b], axis=1)
pds1 = np.round(c[:, 1] * 100)
pds2 = pds1 + np.round(c[:, 2] * 100)
pds = np.stack([pds1, pds2], axis=1)
pds1

array([20., 10., 10.])

In [30]:
pds1 = pds1[:, np.newaxis]

In [33]:
pds1[:,0]

array([20., 10., 10.])

In [17]:
a = np.array([[1,2,3,5],
             [2,4,7,8]])
a.shape

(2, 4)

In [73]:
a = np.zeros((10,10))
b = np.array([1,2,3,4,5,6,7,8,9,10])
c = np.array([0,1,1,1,1,1,1,1,1,0])
random_matrix = np.random.rand(10,10)
mask = np.arange(10) < b[:, np.newaxis]
a[mask] = random_matrix[mask]
a

array([[0.5603889 , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.42979385, 0.39402603, 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.37658714, 0.17419386, 0.73934598, 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.05364311, 0.89459477, 0.46135142, 0.24629656, 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.77771014, 0.98940701, 0.50228901, 0.79857415, 0.58114785,
        0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.89784339, 0.59793307, 0.36127116, 0.40181839, 0.7941363 ,
        0.34998872, 0.        , 0.        , 0.        , 0.        ],
       [0.29557865, 0.00809744, 0.49890532, 0.17744623, 0.55749315,
        0.04452211, 0.78174907, 0.        , 0.        , 0.        ],
       [0.42849521, 0.47662994, 0.0554673

In [74]:
random_matrix = np.random.rand(10,10)
mask = np.arange(10) < c[:, np.newaxis]
print(mask.shape)

(10, 10)


In [42]:
import numpy as np

# 创建一个示例矩阵
matrix = np.array([[1.1, 2, 3],
                   [3, 8, 0]])

# 打乱每行的元素
np.apply_along_axis(np.random.shuffle, axis=1, arr=matrix)

print(matrix)

[[3.  1.1 2. ]
 [8.  3.  0. ]]


In [43]:
a = np.ones((100,100))
a

array([[1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       ...,
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.]])

In [51]:
b = np.zeros((2,100,100))
b[0] = a
b[1,1] = 1
b

array([[[1., 1., 1., ..., 1., 1., 1.],
        [1., 1., 1., ..., 1., 1., 1.],
        [1., 1., 1., ..., 1., 1., 1.],
        ...,
        [1., 1., 1., ..., 1., 1., 1.],
        [1., 1., 1., ..., 1., 1., 1.],
        [1., 1., 1., ..., 1., 1., 1.]],

       [[0., 0., 0., ..., 0., 0., 0.],
        [1., 1., 1., ..., 1., 1., 1.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]]])

In [68]:
a = np.array([1,2,3,4])
b,_=a[a>1][:,np.newaxis].shape
b

3

In [70]:
import numpy as np

# 创建一个示例的一维数组
original_array = np.array([1, 2, 3, 4, 5])

# 指定要创建的二维数组的行数
num_rows = 100

# 使用广播创建包含重复一维数组的二维数组
two_dimensional_array = np.tile(original_array, (num_rows, 1))

print(two_dimensional_array)


[[1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]

In [72]:
IDR_m = np.array([10, 10, 10])
IDR_m = IDR_m[np.newaxis,:]
IDR_m[:,1]

array([10])