In [4]:
import numpy as np
from response_spectra import solve_nigam_jennings, integrate_acceleration

ACC_SET = np.loadtxt(r'C:\Users\12734\OneDrive\重要文件\2_SensitivityAnalysis\Sensitivity-PythonCode\sensitivity-code\ResilienceAssessment\MainProcess\地震动\2475year71\ACC.txt')
Sa_SET = np.loadtxt(r'C:\Users\12734\OneDrive\重要文件\2_SensitivityAnalysis\Sensitivity-PythonCode\sensitivity-code\ResilienceAssessment\MainProcess\地震动\2475year71\Sa.txt')

param_set = np.zeros((30, 6))
for flag in range(30):
    ACC = ACC_SET[flag, :] * 9.8 / Sa_SET[flag] * 0.71
    ag = ACC * 9.8
    # 求解 PGA, PGV, PGD
    PGA = ag.max()
    v, d = integrate_acceleration(ag)
    PGV = v.max()
    PGD = d.max()
    # 获取生成地震动的相关参数
    dnt = 0.01
    omg = 2.0 * np.pi / 1.0
    zeta = 0.05
    Sd, Sv, Sa = solve_nigam_jennings(omg, zeta, ag, dnt)
    param = np.array([PGA, PGV, PGD, Sd, Sv, Sa]) 
    param_set[flag, :] = param


In [6]:
np.savetxt('2475year_input.txt', param_set)

In [18]:
import numpy as np

# 创建一个示例的三十行数组
array = np.arange(1, 91).reshape(30, 3)  # 生成一个30行3列的示例数组

# 随机选择一个行
for i in range(10):
    random_row = np.random.choice(array.shape[0])
    print(random_row)
    # 获取选定的行
    selected_row = array[random_row]

    print("随机选择的行：")
    print(selected_row)
    # print(array)

14
随机选择的行：
[43 44 45]
3
随机选择的行：
[10 11 12]
12
随机选择的行：
[37 38 39]
7
随机选择的行：
[22 23 24]
21
随机选择的行：
[64 65 66]
4
随机选择的行：
[13 14 15]
13
随机选择的行：
[40 41 42]
13
随机选择的行：
[40 41 42]
7
随机选择的行：
[22 23 24]
26
随机选择的行：
[79 80 81]


In [1]:
# 创建合适的 0.71g
from StochasticGroundMotionModeling import StochasticGroundMotionModeling
from response_spectra import solve_nigam_jennings
import numpy as np

flag = 1
while flag:
    ACC, _, _ = StochasticGroundMotionModeling(M=8, R=20, Vs=1223, F=1)
    ag = ACC * 9.8
    zeta = 0.05
    dnt = 0.01
    omg = 2.0 * np.pi / 1.0
    _, _, Sa = solve_nigam_jennings(omg, zeta, ag, dnt)
    print(Sa)
    if Sa > 7.0:
        print(Sa)
        flag = 0
    else:
        pass

1.0911734246916454
1.2150593323942331
3.750553301205849
0.8815767115473917
2.4839050222958905
1.4543248009333845
1.8270626252881919
1.2359511634734717
0.9255269439313273
1.8822410938560026
2.3054193240565093
1.1531825452002111
1.5648014988161008
2.177992670252553
0.917861904144598
1.527025817710526
0.46680264727990517
0.40942119009089784
0.9284562728591808
0.9672204478968023
1.0025723408838159
0.8552821588468233
0.37649997977083716
0.793563791931572
0.8414251589160361
1.2664150483299013
1.959025514460635
1.1979071474316867
1.7498652603898373
2.573890265697558
1.0116361253267885
1.1099065130469894
1.169701620612972
1.5815195743161425
0.7547308980709854
0.5361022199243703
1.3037339394719747
0.8922458529311733
0.8803428827599987
1.0946825817601964
2.41635839479257
1.3073188571734993
0.5963677664439101
0.4733529730097865
1.2785520670120591
1.2025217186571329
2.2204999655584334
1.3202446679692152
1.1356472630008676
1.1324805306251182
1.4757814846812713
0.6780157629815418
1.0198669103941262


c:\ProgramData\miniconda3\envs\py310r\lib\site-packages\numpy\core\fromnumeric.py:86: RuntimeWarning: overflow encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
c:\Users\12734\OneDrive\重要文件\2_SensitivityAnalysis\Sensitivity-PythonCode\sensitivity-code\ResilienceAssessment\MainProcess\StochasticGroundMotionModeling.py:140: RuntimeWarning: overflow encountered in square
  hjd2 = hid**2


1.1442101152904252
1.9604592854275384
0.7831540537972178
1.402923602798237
1.518791830372379
2.03406902384251
1.1919811204815425
0.9776347886375686
0.5853711501711
0.5090460033593803
1.85057628347266
1.1189522756985446
0.7223759829236842
0.8636156198234913
1.5114599023462008
0.47456923479216073
0.46490477975796285
1.0070011596212483
0.5729691329342155
0.6405089385335198
0.7790915634359226
0.5722416969193765
0.7415782795603849
0.21816655985485145
2.2587552410798764
2.7112176232459997
1.6315485998231112
1.4841676718050192
1.5667035426781342
0.7862817679289833
0.8562207679933321
1.2862234707705078
0.3449780150770598
2.156544049198006
1.4818523711488276
2.9146339304586055
1.0594874463017583
0.8336928717019714
2.1493599364916087
2.1935342528081136
2.2982715652697765
3.140139854836976
0.5643188671558591
1.2361538066287874
0.9125691283308995
1.7268461109281545
1.0862147359166485
1.8644674092145608
0.9878944042608676
0.5939970641794646
1.8763744748658413
2.5091542523349704
2.118957891502638
0.

In [1]:
import numpy as np

In [11]:
a = np.array([[1,2,3],[8,3,9],[3,5,19]])  # 2 x 3
amax = np.max(a, axis = 1)
amax

array([ 3,  9, 19])

In [19]:
c = a[:,2]
c

array([ 3,  9, 19])

In [27]:
from scipy.stats import lognorm
mean = 0.01
stddev = 0.5
dist = lognorm(s=stddev, scale=mean)
a = np.array([0.01,0.02,0.01])
# x = np.linspace(0, 0.01 * 2, 200)
# y = dist.cdf(x)
# objPercent = np.interp(0.02, x, y)
# objPercent = round(objPercent * 100)
objPercent = dist.cdf(a)
objPercent = np.round(objPercent * 100)
objPercent

array([50., 92., 50.])

In [33]:
nSample = 1000
objPercent = np.array([50, 92, 50])
probNoRepair = objPercent / 100
nNoRepair = (nSample * probNoRepair).astype(int)
Outputlist = np.zeros((3, 1000))
for i in nNoRepair:
    Outputlist[:, :i] = 1  
Outputlist[1,:][Outputlist[1,:]==1].shape

array([500, 920, 500])

In [38]:
Outputlist = np.zeros((3, 1000))
for i in nNoRepair:
    Outputlist[:, :i] = 1  
Outputlist[1,:][Outputlist[1,:]==1].shape

(920,)

In [40]:
import numpy as np

nSample = 1000
objPercent = np.array([50, 92, 50])
probNoRepair = objPercent / 100
nNoRepair = (nSample * probNoRepair).astype(int)
Outputlist = np.zeros((3, 1000))

# 使用广播和掩码来填充Outputlist
mask = np.arange(1000) < nNoRepair[:, np.newaxis]
Outputlist[mask] = 1

# # 检查Outputlist中第二行的非零元素数量
# non_zero_count = np.count_nonzero(Outputlist[1, :])
# print(non_zero_count)


920


In [1]:
import numpy as np
a = np.array([10,100,50])
b = np.zeros((100, 3, a))
b

TypeError: only integer scalar arrays can be converted to a scalar index

In [29]:
import numpy as np
a = np.array([0.3, 0.4, 0.5])
b = np.array([0.1, 0.3, 0.4])
c = np.stack([(1 - a), (a-b), b], axis=1)
pds1 = np.round(c[:, 1] * 100)
pds2 = pds1 + np.round(c[:, 2] * 100)
pds = np.stack([pds1, pds2], axis=1)
pds1

array([20., 10., 10.])

In [30]:
pds1 = pds1[:, np.newaxis]

In [33]:
pds1[:,0]

array([20., 10., 10.])

In [17]:
a = np.array([[1,2,3,5],
             [2,4,7,8]])
a.shape

(2, 4)

In [73]:
a = np.zeros((10,10))
b = np.array([1,2,3,4,5,6,7,8,9,10])
c = np.array([0,1,1,1,1,1,1,1,1,0])
random_matrix = np.random.rand(10,10)
mask = np.arange(10) < b[:, np.newaxis]
a[mask] = random_matrix[mask]
a

array([[0.5603889 , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.42979385, 0.39402603, 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.37658714, 0.17419386, 0.73934598, 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.05364311, 0.89459477, 0.46135142, 0.24629656, 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.77771014, 0.98940701, 0.50228901, 0.79857415, 0.58114785,
        0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.89784339, 0.59793307, 0.36127116, 0.40181839, 0.7941363 ,
        0.34998872, 0.        , 0.        , 0.        , 0.        ],
       [0.29557865, 0.00809744, 0.49890532, 0.17744623, 0.55749315,
        0.04452211, 0.78174907, 0.        , 0.        , 0.        ],
       [0.42849521, 0.47662994, 0.0554673

In [74]:
random_matrix = np.random.rand(10,10)
mask = np.arange(10) < c[:, np.newaxis]
print(mask.shape)

(10, 10)


In [42]:
import numpy as np

# 创建一个示例矩阵
matrix = np.array([[1.1, 2, 3],
                   [3, 8, 0]])

# 打乱每行的元素
np.apply_along_axis(np.random.shuffle, axis=1, arr=matrix)

print(matrix)

[[3.  1.1 2. ]
 [8.  3.  0. ]]


In [43]:
a = np.ones((100,100))
a

array([[1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       ...,
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.]])

In [51]:
b = np.zeros((2,100,100))
b[0] = a
b[1,1] = 1
b

array([[[1., 1., 1., ..., 1., 1., 1.],
        [1., 1., 1., ..., 1., 1., 1.],
        [1., 1., 1., ..., 1., 1., 1.],
        ...,
        [1., 1., 1., ..., 1., 1., 1.],
        [1., 1., 1., ..., 1., 1., 1.],
        [1., 1., 1., ..., 1., 1., 1.]],

       [[0., 0., 0., ..., 0., 0., 0.],
        [1., 1., 1., ..., 1., 1., 1.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]]])

In [68]:
a = np.array([1,2,3,4])
b,_=a[a>1][:,np.newaxis].shape
b

3

In [70]:
import numpy as np

# 创建一个示例的一维数组
original_array = np.array([1, 2, 3, 4, 5])

# 指定要创建的二维数组的行数
num_rows = 100

# 使用广播创建包含重复一维数组的二维数组
two_dimensional_array = np.tile(original_array, (num_rows, 1))

print(two_dimensional_array)


[[1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]

In [72]:
IDR_m = np.array([10, 10, 10])
IDR_m = IDR_m[np.newaxis,:]
IDR_m[:,1]

array([10])