In [1]:
from UQpy.sampling import MonteCarloSampling
from UQpy.run_model.RunModel import RunModel
from UQpy.run_model.model_execution.PythonModel import PythonModel
from UQpy.distributions import Normal
import time
import numpy as np
from python_model import *

In [2]:
pick_model = 'all'

In [3]:
if pick_model in {'scalar', 'vector', 'all'}:
    d = Normal(loc=0, scale=1)
    x_mcs = MonteCarloSampling(distributions=[d, d, d], nsamples=5, random_state=987979)
    names = ['var1', 'var11', 'var111']

    # UQpy returns samples as an ndarray. Convert them to a list for part 1.2
    x_mcs_list = list(x_mcs.samples)
    print("Monte Carlo samples of three random variables from a standard normal distribution.")
    print('Samples stored as an array:')
    print('Data type:', type(x_mcs.samples))
    print('Number of samples:', len(x_mcs.samples))
    print('Dimensions of samples:', np.shape(x_mcs.samples))
    print('Samples')
    print(x_mcs.samples)
    print()
    print('Samples stored as a list:')
    print('Data type:', type(x_mcs_list))
    print('Number of samples:', len(x_mcs_list))
    print('Dimensions of samples:', np.shape(x_mcs_list))
    print('Samples:')
    print(x_mcs_list)

Monte Carlo samples of three random variables from a standard normal distribution.
Samples stored as an array:
Data type: <class 'numpy.ndarray'>
Number of samples: 5
Dimensions of samples: (5, 3)
Samples
[[ 2.23176466 -0.64178252 -0.38551651]
 [ 2.39233592  0.23474428  0.89104532]
 [-0.27088124  0.6625034  -1.66249933]
 [ 0.1157384  -0.09437841  1.04910279]
 [ 0.03322176 -0.09323229 -0.45691713]]

Samples stored as a list:
Data type: <class 'list'>
Number of samples: 5
Dimensions of samples: (5, 3)
Samples:
[array([ 2.23176466, -0.64178252, -0.38551651]), array([2.39233592, 0.23474428, 0.89104532]), array([-0.27088124,  0.6625034 , -1.66249933]), array([ 0.1157384 , -0.09437841,  1.04910279]), array([ 0.03322176, -0.09323229, -0.45691713])]


In [4]:
if pick_model in {'scalar', 'all'}:
    # Call to RunModel - Here we run the model while instantiating the RunModel object.
    t = time.time()
    m = PythonModel(model_script='python_model.py', model_object_name='sum_rvs')
    m12 = RunModel(model=m, samples=x_mcs_list, ntasks=2)
    t_par_python = time.time() - t
    print("\nTime for parallel execution:")
    print(t_par_python)
    print()
    print("The values returned from the Matlab simulation:")
    print(m12.qoi_list)

FileNotFoundError: [Errno 2] No such file or directory: 'qoi.pkl'

In [7]:
import sys
print(sys.version)

3.10.12 | packaged by Anaconda, Inc. | (main, Jul  5 2023, 19:01:18) [MSC v.1916 64 bit (AMD64)]


In [8]:
!pip list

Package           Version
----------------- -------
asttokens         2.0.5
backcall          0.2.0
beartype          0.9.1
colorama          0.4.6
comm              0.1.2
contourpy         1.1.0
cycler            0.11.0
debugpy           1.5.1
decorator         5.1.1
executing         0.8.3
fire              0.5.0
fonttools         4.41.1
ipykernel         6.19.2
ipython           8.12.0
jedi              0.18.1
joblib            1.3.1
jupyter_client    8.1.0
jupyter_core      5.3.0
kiwisolver        1.4.4
matplotlib        3.7.2
matplotlib-inline 0.1.6
mpi4py            3.1.4
nest-asyncio      1.5.6
numpy             1.25.0
packaging         23.0
pandas            2.0.3
parso             0.8.3
pickleshare       0.7.5
Pillow            10.0.0
pip               23.2.1
platformdirs      2.5.2
prompt-toolkit    3.0.36
psutil            5.9.0
pure-eval         0.2.2
Pygments          2.15.1
pyparsing         3.0.9
python-dateutil   2.8.2
pytz              2023.3
pywin32           305.1
py

This is the python_model.py:

In [ ]:
import numpy as np


def sum_rvs(samples=None):
    x = np.sum(samples, axis=1)
    return x